FROM ruby:2.7.4
RUN apt-get update
RUN apt-get install -y build-essential \
  libpq-dev \
  sudo
WORKDIR /backend
COPY Gemfile /backend/
RUN bundle install
COPY entrypoint.prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.prod.sh
ENTRYPOINT ["entrypoint.prod.sh"]
EXPOSE 3000
CMD bundle exec unicorn -E production -c config/unicorn.rb -D
