version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  backend:
    build:
    # build context
      context: .
    # -f に相当。contextがルート
      dockerfile: Dockerfile
    volumes:
      - '.:/backend/'
    ports:
      - '8000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ENV['DB_PASSWORD']
    ports:
      - '3306:3306'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server"]
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
