version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  backend:
    build:
    # build context
      context: .
    # -f に相当
      dockerfile: Dockerfile
    volumes:
      - '.:/backend/'
    ports:
      - '8000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ENV['DB_PASSWORD']
    ports:
      - '3306:3306'
