FROM ruby:3.2.5
ENV TZ Asia/Tokyo
RUN apt-get update
RUN apt-get install -y build-essential \
  libpq-dev \
  sudo
WORKDIR /backend
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install --without test development
COPY . .
COPY entrypoint.prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.prod.sh
ENTRYPOINT ["entrypoint.prod.sh"]
EXPOSE 3000
CMD ["unicorn", "-p", "3000", "-c", "config/unicorn.rb", "-E", "production"]
