version: 2.1
executors:
  backend_container:
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: 'test'
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_PASSWORD: password
      DB_USER: root
    working_directory: ~/backend

commands:
  install_bundler:
    description: Bundler install
    steps:
      - run: gem install bundler -v 2.1.4

jobs:
  fetch_source_code:
    executor:
      name: backend_container
    steps:
      - checkout
      - save_cache:
          key: v1-backend-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/backend
  bundle_dependencies:
    executor:
      name: backend_container
    steps:
      - restore_cache:
          key: v1-backend-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - install_bundler
      - run:
          name: Bundle Install Dependencies
          command: |
            bundle install --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rspec:
    executor:
      name: backend_container
    parallelism: 2
    steps:
      - restore_cache:
          key: v1-backend-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Waiting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      - install_bundler
      - run:
          command: |
            bundle install
      - run:
          name: create database
          command: bundle exec rails db:create
      - run:
          name: migrate database
          command: bundle exec rails db:migrate
      - run:
          name: Parallel RSpec
          command: |
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --format progress --format RspecJunitFormatter -o tmp/test-results/rspec.xml -- $TESTFILES
      - store_test_results:
          path: tmp/test-results

  rubocop:
    executor:
      name: backend_container
    steps:
      - restore_cache:
          key: v1-backend-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - install_bundler
      - run:
          command: |
            bundle install
      - run:
          name: Execute rubocop
          command: |
            bundle exec rubocop -a

workflows:
  version: 2
  build:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
