FROM nginx:1.21.3
RUN apt-get update && \
  apt-get install -y apt-utils \
  locales && \
  sed -i -e 's/# ja_JP.UTF-8/ja_JP.UTF-8/g' /etc/locale.gen && \
  locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LC_TIME C
ADD nginx.conf /etc/nginx/backend.conf
ADD default.conf /etc/nginx/conf.d/default.conf
